### ISSUE TITLE
Build.scala set-up example

### ISSUE THREAD

**Issue by mayacr86** [sbt/sbt-proguard#7]
Please provide an example in the documentation about how to set-up the plugin in a Build.scala file.

**Comment by pvlugter** [comment]
Have you looked at the sample projects? This one uses a Build.scala: https://github.com/sbt/sbt-proguard/blob/v0.2.2/src/sbt-test/proguard/akka/project/SampleBuild.scala

You add the plugin in the same way (to `project/plugins.sbt`), add the proguardSettings to projects, and otherwise configuration is very similar.

**Comment by pvlugter** [comment]
You may find it useful to look at the sbt documentation for differences between Build.scala and build.sbt builds: http://www.scala-sbt.org/documentation.html

**Comment by mayacr86** [comment]
Sorry, I didn't take a look at all the sample (facepalm). Thanks!
